---
- include: RedHat6.yml
  when: (ansible_os_family == "RedHat") and
        (ansible_distribution_major_version|int == 6)

- include: RedHat7.yml
  when: (ansible_os_family == "RedHat") and
        (ansible_distribution_major_version|int == 7)

- include: Debian.yml
  when: ((ansible_distribution == "Debian") and
        (ansible_distribution_major_version|int >= 7)) or
        ((ansible_distribution == "Ubuntu") and
        (ansible_distribution_major_version|int >= 16))

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777
  become: yes
  tags: ["docker","docker-compose"]

- name: Configure dockerd systemd config
  template:
    src: docker-systemd.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
  become: yes
  notify:
    - systemctl daemon-reload
    - restart docker
  when: (ansible_service_mgr == "systemd") and
        (docker_startup_options is defined) and
        (docker_startup_options != "")
  tags: ["docker","configuration"]

- name: Configure docker metrics publishing
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  become: yes
  notify:
    - restart docker
  # when: docker_metrics_enabled
  tags: ["docker","configuration"]

- name: Create docker group
  group:
    name: "{{ docker_group }}"
  become: yes
  notify: restart docker
  tags: ["docker","groups"]

- name: Add users to docker group
  user:
    name: "{{ item }}"
    append: yes
    groups: "{{ docker_group }}"
  with_items: "{{ docker_users }}"
  become: yes
  notify: restart docker
  tags: ["docker","users"]

- name: Enable or disable docker
  service:
    name: "{{ docker_service_name }}"
    enabled: "{{ docker_service_enabled }}"
  become: yes
  tags: ["docker","service"]

- name: Start or stop docker
  service:
    name: "{{ docker_service_name }}"
    state: "{{ docker_service_state }}"
  become: yes
  register: start_stop_docker
  tags: ["docker","service"]

- name: Adding existing user '{{ ansible_user }}' to group docker
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: yes

- meta: flush_handlers
